-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 17:49:48 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `store_db` ;

-- -----------------------------------------------------
-- Table `store_db`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome_categoria` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `numero_celular` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `data_nascimento` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `enderecos_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `store_db`.`clientes` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`compras` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NULL DEFAULT NULL,
  `data_hora_compra` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `desconto_aplicado` DECIMAL(5,2) NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(255) NULL DEFAULT NULL,
  `total_compra` DECIMAL(10,2) NULL DEFAULT NULL,
  `id_endereco_envio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `id_cliente` (`id_cliente` ASC) VISIBLE,
  INDEX `id_endereco_envio` (`id_endereco_envio` ASC) VISIBLE,
  CONSTRAINT `compras_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `store_db`.`clientes` (`id_cliente`),
  CONSTRAINT `compras_ibfk_2`
    FOREIGN KEY (`id_endereco_envio`)
    REFERENCES `store_db`.`enderecos` (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`subcategorias` (
  `id_subcategoria` INT NOT NULL AUTO_INCREMENT,
  `id_categoria` INT NULL DEFAULT NULL,
  `nome_subcategoria` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_subcategoria`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `subcategorias_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `store_db`.`categorias` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `id_subcategoria` INT NULL DEFAULT NULL,
  `modelo` VARCHAR(255) NULL DEFAULT NULL,
  `fabricante` VARCHAR(255) NULL DEFAULT NULL,
  `preco_base` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantidade_disponivel` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `id_subcategoria` (`id_subcategoria` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`id_subcategoria`)
    REFERENCES `store_db`.`subcategorias` (`id_subcategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`comprasitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`comprasitens` (
  `id_compra` INT NOT NULL,
  `id_produto` INT NOT NULL,
  `quantidade_comprada` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`, `id_produto`),
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `comprasitens_ibfk_1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `store_db`.`compras` (`id_compra`),
  CONSTRAINT `comprasitens_ibfk_2`
    FOREIGN KEY (`id_produto`)
    REFERENCES `store_db`.`produtos` (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `store_db`.`numerosserie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store_db`.`numerosserie` (
  `id_numero_serie` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NULL DEFAULT NULL,
  `numero_serie` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_numero_serie`),
  INDEX `id_produto` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `numerosserie_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `store_db`.`produtos` (`id_produto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
